### ISSUE TITLE
Minimal Opensearch Template

### ISSUE THREAD

**Issue by ng-druid** [rollthecloudinc/hedge#222]

**Comment by ng-druid** [comment]
Can you create me a cloudformation template to stand-up a minimal opensearch instance using the smallst node?

**Comment by classifieds-dev** [comment]
No, Amazon OpenSearch Service (formerly Elasticsearch) does not require you to explicitly set a "master user" and password unless you enable the fine-grained access control feature. By default, OpenSearch uses IAM policies for access control. However, if you want to configure a master user and password for secure access through fine-grained access control, you can include additional properties in your CloudFormation template.

Here is an updated version of the CloudFormation template with fine-grained access control enabled, including a master user and password:

---

### Updated CloudFormation Template

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal OpenSearch instance using the smallest node type (t3.small.search) with fine-grained access control enabled.

Resources:
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: minimal-opensearch
      EngineVersion: OpenSearch_2.5
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      AdvancedSecurityOptions:
        Enabled: true # Enable fine-grained access control
        InternalUserDatabaseEnabled: true # Use the OpenSearch internal user database
        MasterUserOptions:
          MasterUserName: admin # Define the master username
          MasterUserPassword: !Sub '${MasterPassword}' # Include the master password
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'

Parameters:
  MasterPassword:
    Type: String
    Description: Master user password for OpenSearch fine-grained access control
    NoEcho: true # Hide sensitive information in CloudFormation outputs
    MinLength: 8
    MaxLength: 32
    AllowedPattern: '[A-Za-z0-9@!?*#_+=^.-]+'
    ConstraintDescription: Password must be 8-32 characters long and can include letters, numbers, and special characters.

Outputs:
  OpenSearchEndpoint:
    Description: Endpoint of the OpenSearch domain
    Value: !GetAtt OpenSearchDomain.Endpoint
```

---

### Key Changes in the Updated Template:

1. **Fine-Grained Access Control** (`AdvancedSecurityOptions`):
   - `Enabled`: Enables fine-grained access control for better security.
   - `InternalUserDatabaseEnabled`: Uses the internal OpenSearch user database to authenticate users.
   - `MasterUserOptions`: Specifies a master username and password for administrative access to the OpenSearch cluster.

2. **`MasterUserPassword`**:
   - The `MasterPassword` parameter allows you to define the master password securely without hardcoding it.
   - `NoEcho`: Ensures the password is not displayed in plaintext in AWS CloudFormation outputs or the AWS Management Console.

3. **Password Constraints**:
   - The `MasterPassword` parameter includes constraints to ensure strong security.

---

### Important Notes:
- In this updated template, the access policy (`es:*`) is still open to all accounts. You should modify it to limit access only to authorized users or roles.
- The `MasterUserPassword` should be kept secret (e.g., managed via AWS Secrets Manager or securely stored).
- Fine-grained access control allows you to define detailed access permissions for users and roles within OpenSearch, providing flexibility and security.

If you need further help with securing the cluster, let me know!

**Comment by ng-druid** [comment]
Can you now create me a shell script to runit?

**Comment by classifieds-dev** [comment]
Certainly! Below is a shell script designed to deploy the CloudFormation template for the OpenSearch instance using the AWS CLI. The script assumes that you already have AWS CLI installed, properly configured, and authenticated.

---

### Shell Script to Deploy OpenSearch CloudFormation Template

```bash
#!/bin/bash

# Shell script to deploy an AWS CloudFormation template for OpenSearch.

# Set variables
STACK_NAME="MinimalOpenSearchStack"
TEMPLATE_FILE="minimal-opensearch.yml"  # Ensure the YAML template file is in the same directory as this script
REGION="us-east-1"  # Change this to your target AWS region
MASTER_PASSWORD="YourSecurePassword123!"  # Replace with your desired master password

# Create the CloudFormation Stack
echo "Deploying the CloudFormation stack: ${STACK_NAME} in region: ${REGION}..."
aws cloudformation create-stack \
  --stack-name ${STACK_NAME} \
  --template-body file://${TEMPLATE_FILE} \
  --parameters ParameterKey=MasterPassword,ParameterValue=${MASTER_PASSWORD} \
  --capabilities CAPABILITY_NAMED_IAM \
  --region ${REGION}

# Wait for the deployment to complete
if [ $? -eq 0 ]; then
  echo "Stack creation initiated successfully. Waiting for completion..."
  aws cloudformation wait stack-create-complete --stack-name ${STACK_NAME} --region ${REGION}
  
  if [ $? -eq 0 ]; then
    echo "Stack created successfully!"
    
    # Fetch and display the OpenSearch endpoint
    OPENSEARCH_ENDPOINT=$(aws cloudformation describe-stacks \
      --stack-name ${STACK_NAME} \
      --query "Stacks[0].Outputs[?OutputKey=='OpenSearchEndpoint'].OutputValue" \
      --output text \
      --region ${REGION})
      
    echo "OpenSearch Endpoint: ${OPENSEARCH_ENDPOINT}"
  else
    echo "Error: Stack creation failed!"
  fi
else
  echo "Error: Failed to initiate stack creation!"
fi
```

---

### Steps to Use the Script:

1. **Save the Template**:
   - Save the CloudFormation YAML template provided earlier as `minimal-opensearch.yml` in the same directory as the script.

2. **Save the Script**:
   - Save the shell script in a file, e.g., `deploy-opensearch.sh`.
   - Ensure the script is executable: `chmod +x deploy-opensearch.sh`.

3. **Environment Setup**:
   - Ensure AWS CLI is installed and configured (`aws configure`).
   - Replace the `REGION` variable with your target AWS region.
   - Replace the `MASTER_PASSWORD` variable with your desired password for the OpenSearch master user.

4. **Execute the Script**:
   - Run the script: `./deploy-opensearch.sh`.

5. **Monitor Deployment**:
   - The script will wait until the stack creation is complete. Once successful, it retrieves and displays the OpenSearch endpoint.

---

### What the Script Does:
1. **Initiates Stack Creation**:
   - Uses the AWS CLI's `create-stack` command to deploy the CloudFormation template.
   - Passes `MasterPassword` and other necessary parameters.

2. **Waits for Completion**:
   - Monitors the stack creation process using `wait stack-create-complete`.

3. **Fetches OpenSearch Endpoint**:
   - Retrieves the OpenSearch endpoint from the stack outputs.

---

### Notes:
- Ensure adequate IAM permissions for the AWS CLI user to create CloudFormation stacks, as well as OpenSearch domains.
- Avoid hardcoding sensitive information like passwords in scripts; consider external secrets management systems for production environments.
- You may modify the script to include additional error handling or logging.

Let me know if you require further assistance!

**Comment by classifieds-dev** [comment]
The error you are encountering is because the template file (`search_minimal.yaml`) is being executed as a shell script instead of being passed to AWS CloudFormation as a deployment template.

### Why This Happens:
A `.yaml` file is a configuration file, not an executable script. Attempting to run it as a shell script results in errors because the YAML syntax is not understood by the shell interpreter (`bash`).

### Correct Approach:
You need to ensure that the YAML file is **used properly as an input file** for the AWS CLI `create-stack` command in the shell script.

**Solution:**

1. **Save the YAML File Correctly**:
   Ensure the YAML file (`search_minimal.yaml`) is properly saved and formatted. It should not be executed directly. You can verify the file content by running:
   ```bash
   cat search_minimal.yaml
   ```
   The content should match the CloudFormation template provided earlier. Ensure there’s no syntax error in the file.

2. **Use the File in the Deployment Script**:
   Run the shell script (`deploy-opensearch.sh`) that references the YAML file correctly in the `--template-body` parameter.

### Adjusted Workflow:

Here’s how the workflow should go:

#### 1. Save the CloudFormation YAML file:
Save the template as `search_minimal.yaml` in the working directory.

Example contents of `search_minimal.yaml`:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal OpenSearch instance using the smallest node type (t3.small.search) with fine-grained access control enabled.

Resources:
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: minimal-opensearch
      EngineVersion: OpenSearch_2.5
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: admin
          MasterUserPassword: !Sub '${MasterPassword}'
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'

Parameters:
  MasterPassword:
    Type: String
    Description: Master user password for OpenSearch fine-grained access control
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    AllowedPattern: '[A-Za-z0-9@!?*#_+=^.-]+'
    ConstraintDescription: Password must be 8-32 characters long and can include letters, numbers, and special characters.

Outputs:
  OpenSearchEndpoint:
    Description: Endpoint of the OpenSearch domain
    Value: !GetAtt OpenSearchDomain.Endpoint
```

Make sure this file is saved with the correct `.yaml` extension.

---

#### 2. Save the Shell Script:
Save the shell script (`deploy-opensearch.sh`) in the same directory with the following content:

```bash
#!/bin/bash

# Set variables
STACK_NAME="MinimalOpenSearchStack"
TEMPLATE_FILE="search_minimal.yaml"  # YAML file to use (ensure this matches the filename you saved the template as)
REGION="us-east-1"
MASTER_PASSWORD="YourSecurePassword123!"

# Deploy the stack
echo "Deploying the CloudFormation stack: ${STACK_NAME} in region: ${REGION}..."
aws cloudformation create-stack \
  --stack-name ${STACK_NAME} \
  --template-body file://${TEMPLATE_FILE} \
  --parameters ParameterKey=MasterPassword,ParameterValue=${MASTER_PASSWORD} \
  --capabilities CAPABILITY_NAMED_IAM \
  --region ${REGION}

# Wait for the stack creation to complete
if [ $? -eq 0 ]; then
  echo "Stack creation initiated successfully. Waiting for completion..."
  aws cloudformation wait stack-create-complete --stack-name ${STACK_NAME} --region ${REGION}
  
  if [ $? -eq 0 ]; then
    echo "Stack created successfully!"
    
    # Fetch the OpenSearch endpoint
    OPENSEARCH_ENDPOINT=$(aws cloudformation describe-stacks \
      --stack-name ${STACK_NAME} \
      --query "Stacks[0].Outputs[?OutputKey=='OpenSearchEndpoint'].OutputValue" \
      --output text \
      --region ${REGION})
      
    echo "OpenSearch Endpoint: ${OPENSEARCH_ENDPOINT}"
  else
    echo "Error: Stack creation failed!"
  fi
else
  echo "Error: Failed to initiate stack creation!"
fi
```

Ensure both files are saved correctly in the same directory. Then make the script executable:
```bash
chmod +x deploy-opensearch.sh
```

---

#### 3. Execute the Shell Script:
Run the script:
```bash
./deploy-opensearch.sh
```

This will use the YAML file `search_minimal.yaml` as the template file and pass it to AWS CloudFormation for deployment.

---

### Common Issues:

1. **Incorrect File Path**:
   Ensure `search_minimal.yaml` is in the same directory as the script, or provide the correct file path in the `--template-body file://` parameter.

2. **YAML Syntax Errors**:
   Check your YAML template for proper indentation and format. Use tools like `yamllint` to validate it.

3. **AWS CLI Configuration**:
   Ensure the AWS CLI is set up correctly (`aws configure`) and you have sufficient IAM permissions.

If problems persist, share the exact error message for further assistance!

**Comment by classifieds-dev** [comment]
The error message indicates that **node-to-node encryption** must be enabled in your OpenSearch configuration when you use **advanced security options**. This is a security feature that ensures encrypted communication between nodes within the cluster.

---

### How to Resolve the Issue:

You need to modify the CloudFormation template to enable **node-to-node encryption**. Below is the corrected template:

---

### Updated CloudFormation Template

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal OpenSearch instance using the smallest node type (t3.small.search) with fine-grained access control.

Resources:
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: minimal-opensearch
      EngineVersion: OpenSearch_2.5
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: admin
          MasterUserPassword: !Sub '${MasterPassword}'
      EncryptionAtRestOptions:
        Enabled: true # Enable encryption at rest
      NodeToNodeEncryptionOptions:
        Enabled: true # Enable node-to-node encryption
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'

Parameters:
  MasterPassword:
    Type: String
    Description: Master user password for OpenSearch fine-grained access control
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    AllowedPattern: '[A-Za-z0-9@!?*#_+=^.-]+'
    ConstraintDescription: Password must be 8-32 characters long and can include letters, numbers, and special characters.

Outputs:
  OpenSearchEndpoint:
    Description: Endpoint of the OpenSearch domain
    Value: !GetAtt OpenSearchDomain.Endpoint
```

---

### Key Changes to Address the Issue:

1. **`NodeToNodeEncryptionOptions`**:
   - Added the `NodeToNodeEncryptionOptions` property with `Enabled: true`. This ensures that encryption is enabled for communication between OpenSearch nodes.

2. **`EncryptionAtRestOptions`**:
   - Added the `EncryptionAtRestOptions` property with `Enabled: true`. This encrypts the data stored on the OpenSearch EBS volume.

---

### Why Node-to-Node Encryption Is Required:
When you enable **AdvancedSecurityOptions** (fine-grained access control), Amazon OpenSearch Service requires that node-to-node communication and data at rest be encrypted for security reasons.

---

### Steps to Redeploy:
1. **Update the YAML File**:
   Save the updated template to `search_minimal.yaml`.

2. **Run the Script**:
   Use the shell script provided earlier to redeploy the stack. If the stack already exists, delete it before redeploying or use the `update-stack` command:
   ```bash
   aws cloudformation update-stack \
     --stack-name MinimalOpenSearchStack \
     --template-body file://search_minimal.yaml \
     --parameters ParameterKey=MasterPassword,ParameterValue=YourSecurePassword123! \
     --capabilities CAPABILITY_NAMED_IAM \
     --region us-east-1
   ```

---

### Additional Security Considerations:
- **Restrict AccessPolicies**: Update the `AccessPolicies` property to restrict access to specific IAM roles or IP addresses, as the wildcard (`'*'`) opens access to all users.
- **Monitor Costs**: Encryption options may slightly increase the cost, so verify your budget accordingly.

---

Let me know if you encounter further issues!

**Comment by ng-druid** [comment]
Resource handler returned message: "Invalid request provided: You must enable EnforceHTTPS in the domain endpoint options to use advanced security. (Service: OpenSearch, Status Code: 400, Request ID: 57e0e570-7c5b-44cf-8d85-fd378bfa7c85) (SDK Attempt Count: 1)" (RequestToken: fd1df9cb-d357-8828-7558-eac0fd5cfe5d, HandlerErrorCode: InvalidRequest)

**Comment by ng-druid** [comment]
domain creation is hanging t -  Provisioning new nodes
Provisioning new nodes - do you thnk you know what could be causing this and how to fix?

**Comment by classifieds-dev** [comment]
Provisioning new nodes in an OpenSearch domain typically involves tasks like spinning up instances, configuring networking, applying encryption, and initializing the domain. The delay in provisioning could be due to several reasons, including resource constraints, incomplete configurations, or issues with the AWS service itself.

---

### Potential Causes and Fixes

#### **1. AWS Resource Limits**
- **Cause**: If your AWS account is hitting limits on resources like EC2 instances, EBS volumes, or OpenSearch-specific service limits, the nodes may not provision successfully.
- **Fix**:
  1. Check EC2 instance limits in your AWS region:
     ```bash
     aws service-quotas list-service-quotas --service-code ec2
     ```
  2. If the `t3.small.search` instance type is unavailable, request a quota increase or try a different instance type.
  3. Review OpenSearch-specific limits:
     ```bash
     aws service-quotas list-service-quotas --service-code opensearch
     ```
  4. Ensure the quota for maximum instances or EBS storage for OpenSearch is sufficient for the domain.

---

#### **2. Networking Issues**
- **Cause**: If the OpenSearch domain is set up in a VPC, misconfigured subnets, security groups, or route tables could delay node provisioning.
- **Fix**:
  1. Verify the VPC configuration, ensuring selected subnets and availability zones are reachable.
  2. Confirm security group rules allow all necessary communication (e.g., port `443` for HTTPS, port `9300` for node-to-node communication).
  3. Ensure the VPC endpoint for OpenSearch is set up correctly if you're trying to enforce strict network boundaries.

---

#### **3. Encryption Options Dependencies**
- **Cause**: The template includes dependencies that require additional setup, such as enabling encryption at rest, node-to-node encryption, and HTTPS enforcement. AWS takes longer to provision encrypted resources.
- **Fix**:
  1. Review the CloudFormation events using the following:
     ```bash
     aws cloudformation describe-stack-events --stack-name MinimalOpenSearchStack
     ```
  2. If encryption options are causing delays, ensure the `AWS::OpenSearchService::Domain` resource in your template explicitly enables dependencies.

---

#### **4. AWS Region-Specific Issues**
- **Cause**: Certain resources or configurations are slower to provision depending on the region (e.g., less frequent updates from AWS or backend delays in specific regions).
- **Fix**:
  - If you deployed in a low-capacity region, try deploying in a high-capacity region, such as `us-east-1` or `us-west-2`.

---

#### **5. Issues With OpenSearch Domain or Template**
- **Cause**: Some configurations in the CloudFormation template might cause delays if dependencies are not set up correctly or if AWS attempts to validate conflicting settings.
- **Fix**:
  1. Simplify the configuration to test the provisioning:
     - Temporarily disable advanced security options or encryption to isolate the issue.
     - Keep `t3.small.search` as the instance type to reduce resource footprint.
  2. Deploy the template with minimal settings:
     ```yaml
     AdvancedSecurityOptions:
       Enabled: false
     NodeToNodeEncryptionOptions:
       Enabled: false
     DomainEndpointOptions:
       EnforceHTTPS: false
     ```
     Then verify if the nodes provision faster in this scenario.

---

#### **6. Service Outage or AWS Backend Issues**
- **Cause**: AWS OpenSearch Service may experience outages or delays. These are rare but could cause prolonged provisioning timelines.
- **Fix**:
  - Check AWS Service Health Dashboard to verify if there are issues specific to OpenSearch in your region:
    https://health.aws.amazon.com/health/home
  - If there’s no issue reported, contact AWS Support for assistance.

---

#### **7. Scalability Configuration**
- **Cause**: Scaling configurations may request more nodes than the region or your quota allows.
- **Fix**:
  - Check `ClusterConfig` properties in the YAML template:
    ```yaml
    ClusterConfig:
      InstanceCount: 1 # Single node to minimize scaling delays
    ```

---

### Troubleshooting Steps

1. **Review Events**:
   Run the following AWS CLI command to check domain creation progress:
   ```bash
   aws opensearch describe-domain --domain-name minimal-opensearch
   ```
   This will show domain configuration status and highlight any issues during provisioning.

2. **Pause Security Configurations**:
   Temporarily disable encryption and advanced security options to identify potential bottlenecks with security-related features:
   ```yaml
   AdvancedSecurityOptions:
     Enabled: false
   NodeToNodeEncryptionOptions:
     Enabled: false
   ```
   Restart the stack deployment and test if provisioning completes successfully.

3. **Cross-Check AWS Console**:
   Navigate to the OpenSearch domain in the AWS Management Console, and check the domain creation status/logs. If the provisioning is stuck, AWS may provide diagnostic details directly.

4. **Contact AWS Support**:
   If you cannot identify the issue, open a case with AWS Support. Provide relevant details, such as the stack events and the status output from the `describe-domain` command.

---

### Preventive Actions

- **Region Selection**: Deploy in regions with higher resource capacity and availability (e.g., `us-east-1`).
- **Optimize Template**: Start with a simple OpenSearch configuration before introducing additional features like fine-grained access control and encryption.
- **AWS Limits**: Periodically check and request necessary AWS quota increases.

If the issue persists or you need more detailed troubleshooting, share the specific provisioning status or logs for further assistance!

**Comment by classifieds-dev** [comment]
To integrate Amazon Cognito authentication with your OpenSearch domain, you can leverage **Cognito User Pool** and **Cognito Identity Pool** for user authentication and authorization. Amazon OpenSearch supports user authentication via Cognito as part of its **Advanced Security Options**. Below is an updated CloudFormation template that includes Cognito integration.

---

### Updated CloudFormation Template with Cognito Authentication

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal OpenSearch domain with Cognito authentication and proper security.

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: OpenSearchUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      MfaConfiguration: OPTIONAL

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: OpenSearchUserPoolClient
      GenerateSecret: true

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: OpenSearchIdentityPool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ProviderName: !Sub 'cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}'
          ClientId: !Ref CognitoUserPoolClient

  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: minimal-opensearch
      EngineVersion: OpenSearch_2.5
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      EncryptionAtRestOptions:
        Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      DomainEndpointOptions:
        EnforceHTTPS: true
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: admin
          MasterUserPassword: !Ref MasterPassword
        CognitoOptions:
          Enabled: true
          UserPoolId: !Ref CognitoUserPool
          IdentityPoolId: !Ref CognitoIdentityPool
          RoleArn: !GetAtt CognitoRole.Arn
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: !Sub 'arn:${AWS::Partition}:es:${AWS::Region}:${AWS::AccountId}:domain/minimal-opensearch/*'

  CognitoRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: OpenSearchCognitoRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'cognito-identity.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: OpenSearchCognitoAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - es:ESHttpGet
                  - es:ESHttpPost
                  - es:ESHttpPut
                Resource: !Sub 'arn:${AWS::Partition}:es:${AWS::Region}:${AWS::AccountId}:domain/minimal-opensearch/*'

Parameters:
  MasterPassword:
    Type: String
    Description: Master user password for OpenSearch fine-grained access control
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    AllowedPattern: '[A-Za-z0-9@!?*#_+=^.-]+'
    ConstraintDescription: Password must be 8-32 characters long and include valid characters.

Outputs:
  OpenSearchEndpoint:
    Description: Endpoint of the OpenSearch domain.
    Value: !GetAtt OpenSearchDomain.Endpoint

  CognitoUserPoolId:
    Description: Cognito User Pool ID.
    Value: !Ref CognitoUserPool

  CognitoIdentityPoolId:
    Description: Cognito Identity Pool ID.
    Value: !Ref CognitoIdentityPool
```

---

### Key Components Added for Cognito Authentication:

#### 1. **Cognito User Pool**:
- Creates a Cognito User Pool (`CognitoUserPool`) for managing users.
- Configures password policies for user authentication.

#### 2. **Cognito User Pool Client**:
- Creates a Cognito User Pool Client (`CognitoUserPoolClient`) for interacting with the User Pool.

#### 3. **Cognito Identity Pool**:
- Creates a Cognito Identity Pool (`CognitoIdentityPool`) for federated identities that interact with OpenSearch.

#### 4. **IAM Role for Cognito**:
- `CognitoRole` is created to allow Cognito identities to assume permissions for interacting with the OpenSearch domain.
- The policy attached to the role grants permissions (`es:ESHttp*`) for accessing the OpenSearch domain.

#### 5. **Integration with OpenSearch Domain**:
- Configures OpenSearch's `AdvancedSecurityOptions` to use Cognito for authentication via the `CognitoOptions`:
  - `UserPoolId` references the Cognito User Pool.
  - `IdentityPoolId` references the Cognito Identity Pool.
  - `RoleArn` references the IAM Role.

---

### How Cognito Authentication Works:
1. The Cognito User Pool authenticates users using the defined password policies.
2. The Cognito Identity Pool federates identities for authenticated users and assigns the `CognitoRole` to them.
3. The OpenSearch domain validates incoming requests via Cognito authentication using `CognitoOptions`.

---

### How to Deploy the Updated Template:

1. **Save the Template File**:
   Save the updated template as `search_minimal_with_cognito.yaml`.

2. **Deploy CloudFormation Stack**:
   Use AWS CLI to deploy the stack:
   ```bash
   aws cloudformation create-stack \
     --stack-name OpenSearchWithCognitoStack \
     --template-body file://search_minimal_with_cognito.yaml \
     --parameters ParameterKey=MasterPassword,ParameterValue=YourSecurePassword123! \
     --capabilities CAPABILITY_NAMED_IAM \
     --region us-east-1
   ```

3. **Monitor Stack Creation**:
   Monitor events to check for successful deployment:
   ```bash
   aws cloudformation describe-stack-events \
     --stack-name OpenSearchWithCognitoStack \
     --region us-east-1
   ```

4. **Validate Cognito Integration**:
   - Navigate to the OpenSearch domain in the AWS Management Console.
   - Confirm that Cognito authentication is enabled under "Security" in the OpenSearch domain settings.

---

### Notes on Using Cognito:
- Replace `YOUR_ACCOUNT_ID` with the actual AWS account ID in the template.
- Ensure the IAM role attached to OpenSearch (`CognitoRole`) grants permissions necessary for interaction.
- Configure additional user management, such as creating test users in the Cognito User Pool via AWS CLI, Console, or SDK.

---

Let me know if you need further assistance with customizing the template or testing Cognito integration!
