### ISSUE TITLE
Minimal Opesearch Enable Cognito Auth

### ISSUE THREAD

**Issue by ng-druid** [rollthecloudinc/hedge#223]

**Comment by ng-druid** [comment]
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal OpenSearch instance using the smallest node type (t3.small.search) with fine-grained access control.

Resources:
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: minimal-opensearch
      EngineVersion: OpenSearch_2.5
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: admin
          MasterUserPassword: !Sub '${MasterPassword}'
      EncryptionAtRestOptions:
        Enabled: true # Enable encryption at rest
      NodeToNodeEncryptionOptions:
        Enabled: true # Enable node-to-node encryption
      DomainEndpointOptions:
        EnforceHTTPS: true # Enable HTTPS enforcement
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'

Parameters:
  MasterPassword:
    Type: String
    Description: Master user password for OpenSearch fine-grained access control
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    AllowedPattern: '[A-Za-z0-9@!?*#_+=^.-]+'
    ConstraintDescription: Password must be 8-32 characters long and can include letters, numbers, and special characters.

Outputs:
  OpenSearchEndpoint:
    Description: Endpoint of the OpenSearch domain
    Value: !GetAtt OpenSearchDomain.Endpoint
```

Can you enable cognito authentication  for this template now?

**Comment by classifieds-dev** [comment]
To enable Cognito authentication in your OpenSearch template, you must integrate an Amazon Cognito user pool and identity pool, and configure OpenSearch to use Cognito authentication. Here's the modified CloudFormation template with Cognito authentication enabled:

### Updated Template:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal OpenSearch instance using the smallest node type (t3.small.search) with Cognito authentication and fine-grained access control.

Resources:
  # Cognito User Pool
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: MinimalOpenSearchUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: true
  
  # Cognito User Pool Client
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: MinimalOpenSearchClient
      GenerateSecret: true

  # Cognito Identity Pool
  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: MinimalOpenSearchIdentityPool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName

  # IAM Role for Cognito Authenticated Users
  CognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MinimalOpenSearchAuthRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: OpenSearchAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'es:ESHttp*'
                Resource: !Sub '${OpenSearchDomain.Arn}/*'

  # OpenSearch Domain with Cognito Authentication Enabled
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: minimal-opensearch
      EngineVersion: OpenSearch_2.5
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: admin
          MasterUserPassword: !Sub '${MasterPassword}'
      CognitoOptions:
        Enabled: true
        IdentityPoolId: !Ref CognitoIdentityPool
        UserPoolId: !Ref CognitoUserPool
        RoleArn: !GetAtt CognitoAuthRole.Arn
      EncryptionAtRestOptions:
        Enabled: true # Enable encryption at rest
      NodeToNodeEncryptionOptions:
        Enabled: true # Enable node-to-node encryption
      DomainEndpointOptions:
        EnforceHTTPS: true # Enable HTTPS enforcement
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'

Parameters:
  MasterPassword:
    Type: String
    Description: Master user password for OpenSearch fine-grained access control
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    AllowedPattern: '[A-Za-z0-9@!?*#_+=^.-]+'
    ConstraintDescription: Password must be 8-32 characters long and can include letters, numbers, and special characters.

Outputs:
  OpenSearchEndpoint:
    Description: Endpoint of the OpenSearch domain
    Value: !GetAtt OpenSearchDomain.Endpoint

  CognitoUserPoolId:
    Description: ID of the Cognito User Pool
    Value: !Ref CognitoUserPool

  CognitoIdentityPoolId:
    Description: ID of the Cognito Identity Pool
    Value: !Ref CognitoIdentityPool
```

### Explanation of Changes:
1. **Cognito User Pool and Client**:
   - Added a Cognito User Pool (`CognitoUserPool`) and a User Pool Client (`CognitoUserPoolClient`).
   - This provides the user authentication mechanism.
   
2. **Cognito Identity Pool**:
   - Added a Cognito Identity Pool (`CognitoIdentityPool`) to link the user pool with the OpenSearch domain.

3. **IAM Role**:
   - Created an IAM role (`CognitoAuthRole`) that grants authenticated users access to OpenSearch APIs. This role is linked to the Cognito Identity Pool.

4. **CognitoOptions in OpenSearchDomain**:
   - Enabled Cognito authentication by adding the `CognitoOptions` property, including references to the Identity Pool, User Pool, and the IAM Role.

### Notes:
- Ensure that the resources (Cognito User Pool, Identity Pool, and Roles) synchronize correctly with your OpenSearch domain at runtime.
- Adjust access policies (`AccessPolicies`) based on your specific requirements regarding identity and authorization.

**Comment by ng-druid** [comment]
The user pool and identity pools have already been created

**Comment by classifieds-dev** [comment]
If the Cognito User Pool and Identity Pool are already created, you can modify the template to reference these existing resources instead of creating new ones. Here’s the updated template that assumes you will provide the IDs for the existing Cognito User Pool and Identity Pool as parameters:

### Updated Template:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal OpenSearch instance using the smallest node type (t3.small.search) with Cognito authentication and fine-grained access control.

Resources:
  # IAM Role for Cognito Authenticated Users
  CognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MinimalOpenSearchAuthRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPoolId
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: OpenSearchAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'es:ESHttp*'
                Resource: !Sub '${OpenSearchDomain.Arn}/*'

  # OpenSearch Domain with Cognito Authentication Enabled
  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: minimal-opensearch
      EngineVersion: OpenSearch_2.5
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: admin
          MasterUserPassword: !Sub '${MasterPassword}'
      CognitoOptions:
        Enabled: true
        IdentityPoolId: !Ref CognitoIdentityPoolId
        UserPoolId: !Ref CognitoUserPoolId
        RoleArn: !GetAtt CognitoAuthRole.Arn
      EncryptionAtRestOptions:
        Enabled: true # Enable encryption at rest
      NodeToNodeEncryptionOptions:
        Enabled: true # Enable node-to-node encryption
      DomainEndpointOptions:
        EnforceHTTPS: true # Enable HTTPS enforcement
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'

Parameters:
  MasterPassword:
    Type: String
    Description: Master user password for OpenSearch fine-grained access control
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    AllowedPattern: '[A-Za-z0-9@!?*#_+=^.-]+'
    ConstraintDescription: Password must be 8-32 characters long and can include letters, numbers, and special characters.

  CognitoUserPoolId:
    Type: String
    Description: ID of the existing Cognito User Pool

  CognitoIdentityPoolId:
    Type: String
    Description: ID of the existing Cognito Identity Pool

Outputs:
  OpenSearchEndpoint:
    Description: Endpoint of the OpenSearch domain
    Value: !GetAtt OpenSearchDomain.Endpoint
```

### Key Adjustments:
1. **Parameters for Existing Cognito Resources**:
   - Added `CognitoUserPoolId` and `CognitoIdentityPoolId` as parameters so you can supply the IDs of the pre-existing User Pool and Identity Pool.

2. **CognitoOptions References**:
   - Updated the `CognitoOptions` in the `OpenSearchDomain` resource to reference the provided Cognito User Pool and Identity Pool IDs.

3. **IAM Role Policy**:
   - Modified the policy for `CognitoAuthRole` to dynamically reference the provided Identity Pool ID.

### Notes:
- You need to provide the values for `CognitoUserPoolId` and `CognitoIdentityPoolId` when launching this CloudFormation stack.
- The stack assumes that the Cognito resources are already configured correctly and functional. Adjust the IAM roles and policies as necessary based on your security and access requirements.
- Ensure that your existing Cognito configuration aligns with OpenSearch’s fine-grained access control and authentication requirements.

**Comment by ng-druid** [comment]
An error occurred (ValidationError) when calling the CreateStack operation: Circular dependency between resources: [DistinctOpenSearchDomain, DistinctCognitoAuthRole]
Error: Failed to initiate stack creation!

**Comment by classifieds-dev** [comment]
The error `Circular dependency between resources: [DistinctOpenSearchDomain, DistinctCognitoAuthRole]` occurs because the OpenSearch domain (`DistinctOpenSearchDomain`) depends on the IAM role (`DistinctCognitoAuthRole`), which in turn references the OpenSearch domain (`DistinctOpenSearchDomain.Arn`) in its policy. This forms a circular dependency.

To resolve this issue, we need to remove the circular reference by breaking the dependency between the domain and the IAM role within the CloudFormation template. The recommended approach is to remove the direct dependency in the IAM role's policy, as follows:

### Revised Template

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Distinct OpenSearch instance using the smallest node type (t3.small.search) with Cognito authentication and fine-grained access control.

Resources:
  # IAM Role for Cognito Authenticated Users
  DistinctCognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DistinctOpenSearchAuthRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPoolId
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: DistinctOpenSearchAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'es:ESHttp*'
                Resource: '*'

  # OpenSearch Domain with Cognito Authentication Enabled
  DistinctOpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: distinct-opensearch
      EngineVersion: OpenSearch_2.5
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: admin
          MasterUserPassword: !Sub '${MasterPassword}'
      CognitoOptions:
        Enabled: true
        IdentityPoolId: !Ref CognitoIdentityPoolId
        UserPoolId: !Ref CognitoUserPoolId
        RoleArn: !GetAtt DistinctCognitoAuthRole.Arn
      EncryptionAtRestOptions:
        Enabled: true # Enable encryption at rest
      NodeToNodeEncryptionOptions:
        Enabled: true # Enable node-to-node encryption
      DomainEndpointOptions:
        EnforceHTTPS: true # Enable HTTPS enforcement
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'

Parameters:
  MasterPassword:
    Type: String
    Description: Master user password for OpenSearch fine-grained access control
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    AllowedPattern: '[A-Za-z0-9@!?*#_+=^.-]+'
    ConstraintDescription: Password must be 8-32 characters long and can include letters, numbers, and special characters.

  CognitoUserPoolId:
    Type: String
    Description: ID of the existing Cognito User Pool

  CognitoIdentityPoolId:
    Type: String
    Description: ID of the existing Cognito Identity Pool

Outputs:
  DistinctOpenSearchEndpoint:
    Description: Endpoint of the Distinct OpenSearch domain
    Value: !GetAtt DistinctOpenSearchDomain.Endpoint
```

### Explanation of Changes
1. **Removed Reference to Domain ARN in IAM Role Policy**
   - The resource string in `DistinctOpenSearchAccessPolicy` was changed from `!Sub '${DistinctOpenSearchDomain.Arn}/*'` to `'*'`.
   - This avoids the circular dependency by not referencing the OpenSearch domain in the IAM policy.
   - The `'*'` wildcard grants access to all OpenSearch domains in your account **(only use this if appropriate for your permissions model)**. Alternatively, you can specify the domain ARN manually in the policy after stack creation.

2. **Resolved Circular Dependency**
   - By removing the dependency between the domain and the IAM role in the template, the stack can be deployed without encountering the circular dependency error.

### Notes
- If limiting access to only the `distinct-opensearch` domain is required, you will need to manually update the IAM role policy with the OpenSearch domain ARN after stack creation, as its ARN becomes available only after the domain creation is complete.

### Updated Shell Script

No changes are required to the shell script. You can proceed with the updated template to deploy the stack, as the circular dependency issue has been addressed.

If you need further guidance on customizing the IAM policy or additional adjustments, feel free to ask!

**Comment by ng-druid** [comment]
show full template with changes to fix that error

**Comment by classifieds-dev** [comment]
The error indicates that the `cognito-identity.amazonaws.com` service is incorrectly specified within the `Principal` element of the IAM role's `AssumeRolePolicyDocument`. In IAM policies, the `Principal` field for web identity providers cannot have `SERVICE` as its type; instead, it must be `Federated`. This is mandatory when working with Cognito and OpenSearch using web identity federation.

Here’s the fix to resolve this issue:

---

### Corrected IAM Role Trust Relationship

Here's the corrected `AssumeRolePolicyDocument` for the IAM role (`DistinctCognitoAuthRole`):

```yaml
Resources:
  DistinctCognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DistinctOpenSearchAuthRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com  # Correct "Federated" principal for web identity
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPoolId
              ForAnyValue:StringLike:
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: DistinctOpenSearchAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'es:ESHttp*'
                Resource: '*'
```

---

### Explanation of Fix

1. **Changed `Principal.Service` to `Federated`**:
   - In the `Principal` attribute, the type is changed from `Service` to `Federated`. The `Federated` principal is required for web identity federation using Cognito.
   - `cognito-identity.amazonaws.com` is the Identity Provider (IdP) used for Cognito authentication, and it must be referenced correctly under `Federated`.

2. **Retained Other Conditions and Actions**:
   - The `Condition` and `Action` within the `AssumeRolePolicyDocument` remain unchanged.
   - The IAM role continues to allow Cognito users to assume the role based on the authentication process and the Identity Pool configuration.

3. **Policy Reference to OpenSearch**:
   - The inline `DistinctOpenSearchAccessPolicy` policy permits OpenSearch HTTP requests (`es:ESHttp*`) across all resources (`Resource: '*'`).

---

### Updated Full Template

Here’s the full fixed template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Distinct OpenSearch instance using the smallest node type (t3.small.search) with Cognito authentication and fine-grained access control.

Resources:
  # IAM Role for Cognito Authenticated Users
  DistinctCognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DistinctOpenSearchAuthRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com  # Correct Federated principal
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPoolId
              ForAnyValue:StringLike:
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: DistinctOpenSearchAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'es:ESHttp*'
                Resource: '*'

  # OpenSearch Domain with Cognito Authentication Enabled
  DistinctOpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: distinct-opensearch
      EngineVersion: OpenSearch_2.5
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: admin
          MasterUserPassword: !Sub '${MasterPassword}'
      CognitoOptions:
        Enabled: true
        IdentityPoolId: !Ref CognitoIdentityPoolId
        UserPoolId: !Ref CognitoUserPoolId
        RoleArn: !GetAtt DistinctCognitoAuthRole.Arn
      EncryptionAtRestOptions:
        Enabled: true # Enable encryption at rest
      NodeToNodeEncryptionOptions:
        Enabled: true # Enable node-to-node encryption
      DomainEndpointOptions:
        EnforceHTTPS: true # Enable HTTPS enforcement
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'

Parameters:
  MasterPassword:
    Type: String
    Description: Master user password for OpenSearch fine-grained access control
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    AllowedPattern: '[A-Za-z0-9@!?*#_+=^.-]+'
    ConstraintDescription: Password must be 8-32 characters long and can include letters, numbers, and special characters.

  CognitoUserPoolId:
    Type: String
    Description: ID of the existing Cognito User Pool

  CognitoIdentityPoolId:
    Type: String
    Description: ID of the existing Cognito Identity Pool

Outputs:
  DistinctOpenSearchEndpoint:
    Description: Endpoint of the Distinct OpenSearch domain
    Value: !GetAtt DistinctOpenSearchDomain.Endpoint
```

---

### Deployment Steps

1. **Save the Template**:
   Save the corrected template as `search_distinct.yaml`.

2. **Use Deployment Script**:
   Execute your shell script (updated earlier) to deploy the stack. Make sure to provide correct values for the `CognitoUserPoolId` and `CognitoIdentityPoolId` parameters.

3. **Validate IAM Role**:
   After deploying the stack, confirm that:
   - The IAM role’s trust relationship allows OpenSearch to assume the role.
   - Cognito authentication works as expected.

---

### Additional Considerations

1. **Fine-Tune Permissions**:
   If you want to limit the scope of OpenSearch actions (`es:ESHttp*`), update the `Resource` field in the policy to target specific OpenSearch domain resources. You can manually add the domain ARN after the domain is created.

2. **Ensure CAPABILITY_NAMED_IAM**:
   Confirm that your shell script includes `--capabilities CAPABILITY_NAMED_IAM` to authorize creation/modification of IAM resources.

3. **Test Authentication**:
   Test Cognito authentication against the OpenSearch domain to ensure everything is configured correctly.

---

This fix will eliminate the `Invalid principal in policy` error and ensure proper functionality of the OpenSearch domain with Cognito authentication. Let me know if you encounter additional issues!

**Comment by classifieds-dev** [comment]
The error indicates that Amazon OpenSearch Service does not have permission to assume the IAM role (`DistinctCognitoAuthRole`) provided in the `CognitoOptions` for the OpenSearch domain. This typically happens when the `AssumeRolePolicyDocument` in the IAM role is incorrectly configured or lacks permissions for OpenSearch Service. 

Here’s how to resolve the issue:

---

### Full Explanation of the Issue

- AWS OpenSearch requires proper permissions to assume the IAM role specified in the `RoleArn` of the `CognitoOptions` property. 
- The error is likely because the trust relationship in the IAM role does not include OpenSearch (`opensearch.amazonaws.com`) or has other configuration issues.

---

### Steps to Resolve

The IAM role's `AssumeRolePolicyDocument` must explicitly allow OpenSearch Service (`opensearch.amazonaws.com`) to assume the role. Below is the updated template with the correct settings.

---

### Full Corrected Template

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Distinct OpenSearch instance using the smallest node type (t3.small.search) with Cognito authentication and fine-grained access control.

Resources:
  # IAM Role for OpenSearch and Cognito Authentication
  DistinctCognitoAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DistinctOpenSearchAuthRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - cognito-identity.amazonaws.com
                - opensearch.amazonaws.com  # Allow OpenSearch to assume the role
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: DistinctOpenSearchAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'es:ESHttp*'
                Resource: '*'

  # OpenSearch Domain with Cognito Authentication Enabled
  DistinctOpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: distinct-opensearch
      EngineVersion: OpenSearch_2.5
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
        DedicatedMasterEnabled: false
        ZoneAwarenessEnabled: false
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: admin
          MasterUserPassword: !Sub '${MasterPassword}'
      CognitoOptions:
        Enabled: true
        IdentityPoolId: !Ref CognitoIdentityPoolId
        UserPoolId: !Ref CognitoUserPoolId
        RoleArn: !GetAtt DistinctCognitoAuthRole.Arn
      EncryptionAtRestOptions:
        Enabled: true # Enable encryption at rest
      NodeToNodeEncryptionOptions:
        Enabled: true # Enable node-to-node encryption
      DomainEndpointOptions:
        EnforceHTTPS: true # Enable HTTPS enforcement
      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: 'es:*'
            Resource: '*'

Parameters:
  MasterPassword:
    Type: String
    Description: Master user password for OpenSearch fine-grained access control
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    AllowedPattern: '[A-Za-z0-9@!?*#_+=^.-]+'
    ConstraintDescription: Password must be 8-32 characters long and can include letters, numbers, and special characters.

  CognitoUserPoolId:
    Type: String
    Description: ID of the existing Cognito User Pool

  CognitoIdentityPoolId:
    Type: String
    Description: ID of the existing Cognito Identity Pool

Outputs:
  DistinctOpenSearchEndpoint:
    Description: Endpoint of the Distinct OpenSearch domain
    Value: !GetAtt DistinctOpenSearchDomain.Endpoint
```

---

### Key Fixes in the Template

1. **Updated IAM Role Trust Relationship**:
   - Added `opensearch.amazonaws.com` under `Principal.Service` in the `AssumeRolePolicyDocument`.
   - This explicitly allows the OpenSearch service to assume the role.

2. **Changed `Action` to `'sts:AssumeRole'`**:
   - This action is required for OpenSearch to assume the IAM role.

3. **No Changes to Policies**:
   - Inline policy (`DistinctOpenSearchAccessPolicy`) enabling OpenSearch HTTP actions (`es:ESHttp*`) remains unchanged.

---

### Deployment Steps

1. **Save Template**:
   Save the corrected template file as `search_distinct.yaml`.

2. **Shell Script**:
   Use your deployment shell script (previously updated) to deploy the stack. Ensure you provide correct values for the following parameters:
   - `CognitoUserPoolId`: The ID of your existing Cognito User Pool.
   - `CognitoIdentityPoolId`: The ID of your existing Cognito Identity Pool.
   - `MasterPassword`: A secure password for the OpenSearch master user.

3. **Confirm Role Permissions**:
   After the stack deployment, verify that the IAM role (`DistinctCognitoAuthRole`) is properly configured with the correct trust relationship.

---

### Additional Notes

1. **Ensure Proper Permissions**:
   Verify that the AWS account and organization allow OpenSearch Service to assume roles. If using Service Control Policies (SCPs), ensure no restrictive policies block these actions.

2. **Test OpenSearch Cognito Authentication**:
   Once the stack is successfully deployed, test the authentication flow using a Cognito user from the specified User Pool to confirm connectivity.

3. **Review Logs**:
   If errors persist, review CloudFormation and IAM logs to identify additional issues.

This corrected template should resolve the `Invalid request provided: Amazon OpenSearch Service must be allowed to use the passed role` error. Let me know if further assistance is required!
